#!/bin/bash

echo "🚀 NOSSA CASA - Deployment Script"
echo "=================================="
echo ""
echo "✅ Build Status:"
ls -lh dist/index.html 2>/dev/null && echo "   Web build: READY (dist/)" || echo "   Web build: NOT FOUND"
echo ""
echo "✅ Test Status:"
npm test -- --passWithNoTests 2>&1 | grep -E "Tests:|Test Suites:" || echo "   Tests not run"
echo ""
echo "📦 Deployment Options:"
echo ""
echo "Option 1: Vercel (Recommended)"
echo "  vercel login"
echo "  cd dist && vercel --prod"
echo ""
echo "Option 2: Netlify"
echo "  netlify login"
echo "  netlify deploy --prod --dir=dist"
echo ""
echo "Option 3: GitHub Pages"
echo "  git push origin main"
echo "  (Enable in Settings > Pages)"
echo ""
echo "📄 Documentation: See DEPLOY_GUIDE.md"
echo ""
echo "Status: ✅ READY FOR DEPLOYMENT"
