// Registo de alterações da app — a fonte das duas vistas da Documentação.
// Vem do protótipo (`design/Nossa Casa App.dc.html`), onde é escrito à mão a
// cada correção. A Documentação gera daqui as novidades por versão e o «Como
// funciona» por área: nada é escrito duas vezes.
//
// Não confundir com `s.registo`, que é o histórico de alterações que a
// FAMÍLIA faz à casa. São duas coisas diferentes, e o ecrã mostrava a segunda
// onde a referência 17 mostra a primeira.
export const APP_VERSION = '1.8.0';

export const REGISTO_APP = [
  // ── 1.8.0 ─────────────────────────────────────────────────────────────────
  { v: '1.8.0', d: '02/09/2026', k: 'novo', a: 'Perfil', t: 'O avatar escolhe-se: dezasseis figuras, a cor do perfil, ou a fotografia da conta Google' },
  { v: '1.8.0', d: '02/09/2026', k: 'novo', a: 'Perfil', t: 'A fotografia da conta Google traz-se sem terminar a sessão' },
  { v: '1.8.0', d: '02/09/2026', k: 'alterado', a: 'Perfil', t: 'O ecrã passou a cinco secções com nome — A Casa, Aparência, Avisos, A App e Apagar Dados' },
  { v: '1.8.0', d: '02/09/2026', k: 'alterado', a: 'Perfil', t: '«Repor Dados de Demonstração» e «Começar de Zero» deixaram de apagar ao toque: pedem a confirmação de todos os administradores da casa' },
  { v: '1.8.0', d: '02/09/2026', k: 'corrigido', a: 'Perfil', t: 'A fotografia da conta ficava guardada e não aparecia em lado nenhum' },
  { v: '1.8.0', d: '02/09/2026', k: 'alterado', a: 'Início', t: 'O avatar passou para junto do nome, e é ele que abre o Perfil' },
  { v: '1.8.0', d: '02/09/2026', k: 'alterado', a: 'Início', t: 'Os dois atalhos do topo saíram: levavam aos mesmos ecrãs que o rodapé e ocupavam o lugar do «Precisa de Si»' },
  { v: '1.8.0', d: '02/09/2026', k: 'alterado', a: 'Tarefas', t: 'Dentro de cada grupo de urgência, a lista passou a ordenar-se pelo prazo — quem acaba primeiro aparece primeiro' },
  { v: '1.8.0', d: '02/09/2026', k: 'alterado', a: 'Início', t: 'Terminar sessão passou para o cabeçalho, à direita — deixou de ser preciso abrir o Perfil para sair' },
  { v: '1.8.0', d: '02/09/2026', k: 'alterado', a: 'A App', t: 'O modo escuro segue o esquema de cor escolhido — a página deixou de ser azul-marinho para os seis' },
  { v: '1.8.0', d: '02/09/2026', k: 'corrigido', a: 'A App', t: 'O rodapé não levava onde dizia: com a Saúde, os Equipamentos, a Gestão ou a Documentação abertos, tocar num separador não saía de lá' },
  { v: '1.8.0', d: '02/09/2026', k: 'corrigido', a: 'A App', t: 'A seta de voltar estava dez pixels mais perto da borda do que todo o resto do ecrã' },
  { v: '1.8.0', d: '02/09/2026', k: 'corrigido', a: 'A App', t: 'As folhas abriam a ocupar a janela toda no monitor, em vez de ficarem dentro da app' },
  { v: '1.8.0', d: '02/09/2026', k: 'corrigido', a: 'A App', t: 'Botões, pastilhas e interruptores mais pequenos do que o mínimo para o dedo — em cinco ecrãs' },
  { v: '1.8.0', d: '02/09/2026', k: 'alterado', a: 'A App', t: 'A marca da casa no cabeçalho ganhou as suas cores, em vez de um cinzento só' },
  { v: '1.8.0', d: '02/09/2026', k: 'corrigido', a: 'A App', t: 'A marca do cabeçalho ficava por fora da coluna e era cortada em quatro dos cinco separadores' },
  { v: '1.8.0', d: '02/09/2026', k: 'corrigido', a: 'A App', t: 'O avatar mudava de tamanho ao mudar de separador — 44 no Início e 36 nos outros' },
  { v: '1.8.0', d: '02/09/2026', k: 'novo', a: 'Tarefas', t: 'Uma tarefa apaga-se — e os pontos que ela já rendeu ficam com a criança' },
  { v: '1.8.0', d: '02/09/2026', k: 'corrigido', a: 'Tarefas', t: 'Toda a tarefa criada na app dizia «undefined» por baixo do título' },
  { v: '1.8.0', d: '02/09/2026', k: 'corrigido', a: 'Tarefas', t: 'Uma criança acrescentada à casa mostrava «NaN pt» na semanada' },
  { v: '1.8.0', d: '02/09/2026', k: 'corrigido', a: 'Tarefas', t: 'A folha do cofre de uma criança abria em branco' },
  { v: '1.8.0', d: '02/09/2026', k: 'novo', a: 'Compras', t: 'Um artigo apaga-se da lista — e os preços que a casa já registou para ele ficam' },
  { v: '1.8.0', d: '02/09/2026', k: 'corrigido', a: 'Compras', t: 'A lista deixava de abrir depois de a casa ter preços registados' },
  { v: '1.8.0', d: '02/09/2026', k: 'corrigido', a: 'Saúde', t: 'Marcar consulta abria um ecrã em branco' },
  { v: '1.8.0', d: '02/09/2026', k: 'alterado', a: 'Saúde', t: 'As especialidades médicas passaram a ser geridas num sítio só — em Marcar Consulta, onde aparecem' },
  { v: '1.8.0', d: '02/09/2026', k: 'corrigido', a: 'Saúde', t: 'Apagar uma especialidade pergunta primeiro, e diz que as consultas já marcadas com ela ficam' },
  { v: '1.8.0', d: '02/09/2026', k: 'corrigido', a: 'Saúde', t: 'O botão de apagar uma especialidade era menor do que o mínimo para o dedo' },
  { v: '1.8.0', d: '02/09/2026', k: 'corrigido', a: 'Saúde', t: 'Renomear uma especialidade trocava o nome na lista e deixava as consultas a apontar para um nome que já não existia' },
  { v: '1.8.0', d: '02/09/2026', k: 'corrigido', a: 'Saúde', t: 'Marcar consulta não punha nada na ficha — o ecrã dizia «Use Marcar Consulta para a primeira» e usá-lo não punha lá nada' },
  { v: '1.8.0', d: '02/09/2026', k: 'corrigido', a: 'Saúde', t: 'A consulta de uma criança aparecia na agenda das outras crianças, e a de um adulto aparecia ao outro' },
  { v: '1.8.0', d: '02/09/2026', k: 'corrigido', a: 'Saúde', t: 'Marcar consulta deixava escolher o outro adulto, cuja ficha não se pode ver' },
  { v: '1.8.0', d: '03/09/2026', k: 'novo', a: 'Saúde', t: 'Médico ou clínica ao marcar uma consulta — o nome passa a aparecer na ficha, no histórico e no PDF exportado' },
  { v: '1.8.0', d: '03/09/2026', k: 'novo', a: 'Saúde', t: 'Nota ao marcar uma consulta, para o que é preciso levar ou saber' },
  { v: '1.8.0', d: '03/09/2026', k: 'novo', a: 'Saúde', t: 'Marcar uma consulta diz quem a vai ver, antes de a marcar' },
  { v: '1.8.0', d: '03/09/2026', k: 'alterado', a: 'Saúde', t: 'O botão passou a «Marcar e Pôr na Agenda», e o «Gerir» das especialidades está ao lado do título' },
  { v: '1.8.0', d: '03/09/2026', k: 'corrigido', a: 'Saúde', t: 'O cartão de uma consulta não abria — «Resolvida», «Pendente», as notas e as receitas eram inalcançáveis' },
  { v: '1.8.0', d: '03/09/2026', k: 'corrigido', a: 'Saúde', t: 'Uma criança recebia a sua própria ficha do servidor; era só a interface a esconder-lha' },
  { v: '1.8.0', d: '03/09/2026', k: 'novo', a: 'Saúde', t: 'As consultas passam a ficar no servidor da casa — e só nele, nunca num servidor fora de casa' },
  { v: '1.8.0', d: '03/09/2026', k: 'alterado', a: 'Saúde', t: 'O dia e a hora de uma consulta passaram a um só campo, e a hora escolhe-se em vez de se escrever' },
  { v: '1.8.0', d: '03/09/2026', k: 'novo', a: 'Saúde', t: 'Anexar um exame, uma receita ou um relatório a uma consulta' },
  { v: '1.8.0', d: '03/09/2026', k: 'novo', a: 'Saúde', t: 'Arquivar uma consulta — sai da lista, não se apaga, e volta com um toque' },
  { v: '1.8.0', d: '02/09/2026', k: 'corrigido', a: 'Gestão da Casa', t: 'As abas tinham espaços mortos entre elas, e um toque ali não acertava em nenhuma' },
  { v: '1.8.0', d: '02/09/2026', k: 'corrigido', a: 'Gestão da Casa', t: 'A faixa de abas cortava a última no telemóvel — «Especialidades» perdia o fim da palavra' },
  // ── 1.7.0 ─────────────────────────────────────────────────────────────────
  { v: '1.7.0', d: '01/09/2026', k: 'corrigido', a: 'A App', t: 'A data era 20 de agosto, sempre — o cabeçalho, os prazos e as garantias contavam a partir daí' },
  { v: '1.7.0', d: '01/09/2026', k: 'corrigido', a: 'Início', t: '«Bom dia» aparecia a qualquer hora, e uma tarefa das 18:00 dizia sempre «falta 3h30»' },
  { v: '1.7.0', d: '01/09/2026', k: 'alterado', a: 'Perfil', t: 'Três esquemas de cor novos — Rosa, Menta e Cinza — com cabeçalhos mais claros' },
  { v: '1.7.0', d: '01/09/2026', k: 'alterado', a: 'Perfil', t: 'A bola do esquema mostra as duas cores separadas na diagonal' },
  { v: '1.7.0', d: '01/09/2026', k: 'novo', a: 'Agenda', t: 'A autorização da agenda da Google liga-se uma vez e fica — deixou de a pedir a cada sessão' },
  { v: '1.7.0', d: '01/09/2026', k: 'corrigido', a: 'Entrada', t: 'O servidor em baixo dizia que a Google não estava configurada; agora diz o que é' },
  { v: '1.7.0', d: '01/09/2026', k: 'corrigido', a: 'Dinheiro', t: 'Abrir o mês punha sempre «Setembro», qualquer que fosse o mês' },
  { v: '1.7.0', d: '01/09/2026', k: 'corrigido', a: 'Tarefas', t: '«Cofre do Mia» — o artigo passa a acompanhar o género de cada membro' },

  // ── 1.6.0 ─────────────────────────────────────────────────────────────────
  { v: '1.6.0', d: '31/08/2026', k: 'novo', a: 'Agenda', t: 'Eventos editam-se e apagam-se, e vão para a agenda da Google nos dois sentidos' },
  { v: '1.6.0', d: '31/08/2026', k: 'novo', a: 'Agenda', t: 'Visibilidade com três níveis: toda a família, só os adultos, ou só eu' },
  { v: '1.6.0', d: '31/08/2026', k: 'corrigido', a: 'Agenda', t: 'Guardar um evento não fazia nada — gravava num campo que nenhum ecrã lê' },
  { v: '1.6.0', d: '31/08/2026', k: 'novo', a: 'Saúde', t: 'Exportar fichas em PDF: uma consulta, uma especialidade, ou tudo' },
  { v: '1.6.0', d: '31/08/2026', k: 'novo', a: 'Saúde', t: 'O PDF pode seguir por correio para outro adulto da casa' },
  { v: '1.6.0', d: '31/08/2026', k: 'novo', a: 'Compras', t: 'O preço escreve-se no corredor, e a ida seguinte já o sabe' },
  { v: '1.6.0', d: '31/08/2026', k: 'novo', a: 'Compras', t: 'A lista diz em que loja sai mais barata, sobre os artigos que conhece nas duas' },
  { v: '1.6.0', d: '31/08/2026', k: 'novo', a: 'A App', t: 'Instala-se no telemóvel a partir do navegador, sem loja de aplicações' },
  { v: '1.6.0', d: '31/08/2026', k: 'novo', a: 'A App', t: 'Datas escrevem-se à mão ou escolhem-se no calendário, em todos os ecrãs' },
  { v: '1.6.0', d: '31/08/2026', k: 'alterado', a: 'A App', t: 'Uma secção sem nada mostra um aviso, em vez de um título a apontar para o vazio' },
  { v: '1.6.0', d: '31/08/2026', k: 'alterado', a: 'Início', t: 'Tocar num evento ou numa tarefa leva ao ecrã dele, já aberto' },
  { v: '1.6.0', d: '31/08/2026', k: 'corrigido', a: 'Entrada', t: 'Entrar com a conta Google — três defeitos, nenhum na configuração' },
  { v: '1.6.0', d: '31/08/2026', k: 'corrigido', a: 'Dinheiro', t: 'Uma casa nova já não herdava o orçamento da família de demonstração' },

  // ── 1.5.0 ─────────────────────────────────────────────────────────────────
  { v: '1.5.0', d: '30/08/2026', k: 'novo', a: 'Gestão da Casa', t: 'A casa configura-se: nome, membros, papéis e quem sai' },
  { v: '1.5.0', d: '30/08/2026', k: 'novo', a: 'Gestão da Casa', t: 'Renomear um membro leva com ele as tarefas, as despesas e o cofre' },
  { v: '1.5.0', d: '30/08/2026', k: 'alterado', a: 'A App', t: 'A casa deixou de ser quatro nomes escritos no código' },

  { v: '1.4.0', d: '25/08/2026', k: 'novo', a: 'Documentação', t: 'Registo de versões e Como funciona, gerados deste registo' },
  { v: '1.4.0', d: '25/08/2026', k: 'novo', a: 'Saúde', t: 'Ficha por membro com episódios, anexos e notas' },
  { v: '1.4.0', d: '25/08/2026', k: 'novo', a: 'Saúde', t: 'Especialidades geridas na Gestão da Casa' },
  { v: '1.4.0', d: '25/08/2026', k: 'alterado', a: 'Compras', t: 'Listas acima de 5 linhas paginam; 10 por página no modo de loja' },
  { v: '1.4.0', d: '25/08/2026', k: 'alterado', a: 'Perfil', t: 'Aspeto e Esquema de Cor num só bloco, com três ícones' },
  { v: '1.4.1', d: '25/08/2026', k: 'alterado', a: 'Perfil', t: 'Gestão da Casa e Saúde com ícones próprios: houseGear e heartPulse' },
  { v: '1.4.1', d: '25/08/2026', k: 'novo', a: 'A App', t: 'Marca da casa no arranque, no ecrã de entrada e no resumo diário' },
  { v: '1.4.1', d: '25/08/2026', k: 'alterado', a: 'Gestão da Casa', t: 'Divisão das despesas passou a alternador' },
  { v: '1.4.1', d: '25/08/2026', k: 'alterado', a: 'Entrada', t: 'Painéis de vidro passaram de preto a Storm Blue — a cor do cabeçalho onde se entra' },
  { v: '1.4.1', d: '26/08/2026', k: 'alterado', a: 'Perfil', t: 'Escala de espaçamento única (2/4/8/16/24) e entradas da casa num só contentor' },
  { v: '1.4.2', d: '26/08/2026', k: 'corrigido', a: 'Gestão da Casa', t: 'PIN sem valor de fábrica, definido por um adulto e nunca mostrado em claro' },
  { v: '1.4.2', d: '26/08/2026', k: 'alterado', a: 'Gestão da Casa', t: 'Membros: a linha abre a ficha, com PIN e papel como linhas dentro dela' },
  { v: '1.4.2', d: '26/08/2026', k: 'corrigido', a: 'Gestão da Casa', t: 'Cinco tentativas de PIN erradas bloqueiam o perfil por um minuto' },
  { v: '1.4.1', d: '26/08/2026', k: 'corrigido', a: 'Perfil', t: 'Documentação passou a linha do bloco A App e os Dados' },
  { v: '1.4.1', d: '25/08/2026', k: 'alterado', a: 'Gestão da Casa', t: 'Concluir removido — a folha grava ao toque e fecha pelo ✕ do cabeçalho' },
  { v: '1.4.1', d: '25/08/2026', k: 'alterado', a: 'Gestão da Casa', t: 'Valor do ponto livre entre 0,01 e 5,00 €; semanada em qualquer dia da semana' },
  { v: '1.4.0', d: '25/08/2026', k: 'corrigido', a: 'Agenda', t: 'Consultas da Saúde passam a aparecer na Agenda de Hoje' },
  { v: '1.4.0', d: '25/08/2026', k: 'corrigido', a: 'Início', t: 'Rodapé desaparecia em algumas janelas — a raiz fechava cedo' },
  { v: '1.4.0', d: '25/08/2026', k: 'corrigido', a: 'Perfil', t: 'Subtítulo do cabeçalho ilegível nos esquemas mais claros' },
  { v: '1.3.0', d: '24/08/2026', k: 'novo', a: 'Dinheiro', t: 'Registar Despesa fora das compras, com envelope e divisão' },
  { v: '1.3.0', d: '24/08/2026', k: 'novo', a: 'Dinheiro', t: 'Fecho do mês guarda o que foi gasto por envelope' },
  { v: '1.3.0', d: '24/08/2026', k: 'novo', a: 'Tarefas', t: 'Prazo com aviso, e urgência que ordena a lista' },
  { v: '1.3.0', d: '24/08/2026', k: 'alterado', a: 'Gestão da Casa', t: 'Papéis editáveis, com validação das transições possíveis' },
  { v: '1.3.0', d: '24/08/2026', k: 'alterado', a: 'Perfil', t: 'Terminar sessão passou a ícone no cabeçalho da folha' },
  { v: '1.2.0', d: '22/08/2026', k: 'novo', a: 'Compras', t: 'Carrinho, últimas 10 compras e preço habitual de cada artigo' },
  { v: '1.2.0', d: '22/08/2026', k: 'novo', a: 'Compras', t: 'Lojas com a sua própria ordem de corredor' },
  { v: '1.2.0', d: '22/08/2026', k: 'alterado', a: 'Compras', t: 'Aba Todos no modo de loja, para não andar secção a secção' },
  { v: '1.2.0', d: '22/08/2026', k: 'alterado', a: 'Dinheiro', t: 'Valores escritos à mão em vez de montantes fixos' },
  { v: '1.1.0', d: '21/08/2026', k: 'novo', a: 'Equipamentos', t: 'Compra, fatura, garantia e manutenções agendadas' },
  { v: '1.1.0', d: '21/08/2026', k: 'novo', a: 'Gestão da Casa', t: 'Rendimento, semanada, divisão e envelopes, só para quem administra' },
  { v: '1.1.0', d: '21/08/2026', k: 'novo', a: 'Tarefas', t: 'Modo criança com PIN: só as suas tarefas e o seu cofre' },
  { v: '1.0.0', d: '20/08/2026', k: 'novo', a: 'Início', t: 'Cinco separadores: Início, Dinheiro, Tarefas, Compras e Agenda' },
  { v: '1.0.0', d: '20/08/2026', k: 'novo', a: 'Agenda', t: 'Calendário com mês expansível e visibilidade por evento' },
  { v: '1.0.0', d: '20/08/2026', k: 'novo', a: 'Perfil', t: 'Entrada com conta Google, dados guardados no dispositivo' },
];

// Novo / Alterado / Corrigido. As cores vêm do tema em quem desenha.
export const TIPOS = {
  novo:      'Novo',
  alterado:  'Alterado',
  corrigido: 'Corrigido',
};
